# Use root/example as user/password credentials
version: "3.1"

services:
  # node:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   command: /usr/local/wait-for-it.sh mongosh:27017 -- npm run dev
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:4000"
  #   networks:
  #     - node_network
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - 8081:8081
    networks:
      - node_network

  digNikola:
    image: nicolaka/netshoot
    networks:
      - node_network

networks:
  node_network:

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/authSource=admin
  #   networks:
  #     - node_network
